#!/usr/bin/env python3
"""docs_index.py: regenerate the script index table at the end of docs/scripts.md.

docs/scripts.md is written by hand and drifts: scripts get added and never
described. This keeps one generated block in it, a table of every engine script
with the first line of its own description, so a new script shows up the day it
lands and the hand-written sections can catch up later.

Listed: every *.py in tools/ (two levels deep; tests/, locale/, __pycache__ and
__init__.py skipped) and every *.py and *.sh in .agents/scripts/ (one level).
Paths that tools/export_public.py excludes from the public repo are left out
too, because docs/ ships there and the block has to match in both trees.

Usage:
  python3 tools/docs_index.py           # rewrite the block in place
  python3 tools/docs_index.py --check   # exit 1 with a summary when the block is stale
"""
import argparse
import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = Path("docs/scripts.md")
START = "<!-- script-index:start -->"
END = "<!-- script-index:end -->"
SECTION = "## Script index"
NOTE = ("_Generated by `tools/docs_index.py` from each script's own docstring or header "
        "comment; run `python3 tools/docs_index.py` after adding a script._")
MAX_DESC = 120
SKIP_DIRS = {"tests", "locale", "__pycache__"}
NO_DESC = "(no description)"


def export_excludes(root=ROOT):
    """EXCLUDE from tools/export_public.py, read without importing it."""
    src = root / "tools" / "export_public.py"
    try:
        tree = ast.parse(src.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return ()
    for node in tree.body:
        if (isinstance(node, ast.Assign) and len(node.targets) == 1
                and isinstance(node.targets[0], ast.Name) and node.targets[0].id == "EXCLUDE"):
            try:
                return tuple(ast.literal_eval(node.value))
            except ValueError:
                return ()
    return ()


def _excluded(rel, excludes):
    return any(rel == e or rel.startswith(e.rstrip("/") + "/") for e in excludes)


def iter_scripts(root=ROOT):
    """Engine scripts as sorted vault-relative POSIX paths."""
    excludes = export_excludes(root)
    found = []
    tools = root / "tools"
    if tools.is_dir():
        for p in tools.glob("*.py"):
            found.append(p)
        for sub in tools.iterdir():
            if sub.is_dir() and sub.name not in SKIP_DIRS and not sub.name.startswith("."):
                found.extend(sub.glob("*.py"))
    scripts = root / ".agents" / "scripts"
    if scripts.is_dir():
        found.extend(scripts.glob("*.py"))
        found.extend(scripts.glob("*.sh"))
    rels = set()
    for p in found:
        if not p.is_file() or p.name == "__init__.py":
            continue
        rel = p.relative_to(root).as_posix()
        if not _excluded(rel, excludes):
            rels.add(rel)
    return sorted(rels)


def _first_comment(lines):
    """First comment line of the header: after the shebang, before any code."""
    for line in lines:
        s = line.strip()
        if not s or s.startswith("#!") or s.startswith("# -*-") or s.lower().startswith("# shellcheck"):
            continue
        if not s.startswith("#"):
            return ""
        text = s.lstrip("#").strip()
        if text:
            return text
    return ""


def _tidy(text):
    text = re.sub("\\s*\u2014\\s*", ", ", text)
    text = re.sub("(\\d)\\s*\u2013\\s*(\\d)", r"\1-\2", text)
    text = re.sub("\\s*\u2013\\s*", ", ", text)
    text = " ".join(text.split()).replace("|", "\\|")
    if len(text) > MAX_DESC:
        text = text[:MAX_DESC - 3].rstrip() + "..."
    return text


def describe(path):
    """One line: the module docstring's first line for Python, the first
    comment after the shebang for shell (and for Python with no docstring)."""
    path = Path(path)
    try:
        source = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return NO_DESC
    text = ""
    if path.suffix == ".py":
        try:
            doc = ast.get_docstring(ast.parse(source))
        except (SyntaxError, ValueError):
            doc = None
        if doc:
            text = next((ln.strip() for ln in doc.splitlines() if ln.strip()), "")
    if not text:
        text = _first_comment(source.splitlines())
    return _tidy(text) or NO_DESC


def render(root=ROOT):
    rows = [f"| `{rel}` | {describe(root / rel)} |" for rel in iter_scripts(root)]
    return "\n".join([START, NOTE, "", "| Path | What it does |", "| --- | --- |", *rows, END])


def current_block(text):
    i, j = text.find(START), text.find(END)
    if i == -1 or j == -1 or j < i:
        return None
    return text[i:j + len(END)]


def updated(text, block):
    old = current_block(text)
    if old is not None:
        return text.replace(old, block, 1)
    return text.rstrip("\n") + f"\n\n{SECTION}\n\n{block}\n"


def _rows(block):
    out = {}
    for line in (block or "").splitlines():
        m = re.match(r"\| `([^`]+)` \| (.*) \|$", line)
        if m:
            out[m.group(1)] = m.group(2)
    return out


def diff_summary(old, new):
    if old is None:
        return ["markers missing: the script index block is not in the file"]
    a, b = _rows(old), _rows(new)
    lines = [f"added: {p}" for p in sorted(b.keys() - a.keys())]
    lines += [f"removed: {p}" for p in sorted(a.keys() - b.keys())]
    lines += [f"description changed: {p}" for p in sorted(a.keys() & b.keys()) if a[p] != b[p]]
    return lines or ["block text differs (layout or note line)"]


def main(argv=None):
    ap = argparse.ArgumentParser(description="Regenerate the script index in docs/scripts.md.")
    ap.add_argument("--check", action="store_true", help="report a stale block and exit 1, write nothing")
    ap.add_argument("--root", type=Path, default=ROOT, help=argparse.SUPPRESS)
    args = ap.parse_args(argv)
    doc = args.root / DOC
    text = doc.read_text(encoding="utf-8")
    block = render(args.root)
    old = current_block(text)
    if args.check:
        if old == block:
            print(f"{DOC}: script index is current")
            return 0
        print(f"{DOC}: script index is stale; run python3 tools/docs_index.py")
        for line in diff_summary(old, block):
            print(f"  {line}")
        return 1
    new = updated(text, block)
    if new != text:
        doc.write_text(new, encoding="utf-8")
        print(f"{DOC}: script index rewritten ({len(_rows(block))} scripts)")
    else:
        print(f"{DOC}: script index already current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
