#!/usr/bin/env python3
"""Export the public engine repo from this vault (open-source plan, Phase 1).

The export is a WHITELIST copy into a fresh directory. It never derives the
public tree by deleting from the private one, because the private repo's
content and history must not travel. Nothing here touches git.

  python3 tools/export_public.py                # dry run: list what would ship
  python3 tools/export_public.py --out ../brainless-public   # write the tree

After writing, the script scans the result for leaks (identity numbers, keys,
private e-mail addresses, the owner's name outside PROFILE stubs) and exits
non-zero if it finds any. Review the report, then `git init` in the output
directory yourself.
"""
import argparse
import os
import re
import shutil
import sys
import unicodedata

VAULT = os.environ.get("BRAINLESS_VAULT") or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Directories copied whole (relative to the vault). Sub-paths in EXCLUDE are dropped.
SHIP_DIRS = [
    "tools",
    ".agents/scripts",
    ".agents/systemd",
    ".agents/buzz",
    ".agents/skills",
    ".claude/commands",
    ".gemini/commands",
    ".wiki/_commands",
    "_Templates",
    "docs",
]
# README.public.md ships as README.md (the private README describes one deployment).
RENAMES = {"README.public.md": "README.md"}
SHIP_FILES = [
    "README.public.md",
    "install.sh",
    "bin/brainless",
    "requirements.txt",
    "requirements-core.txt",
    "requirements-search.txt",
    ".env.example",
    "LICENSE",
    "CHANGELOG.md",
    "VERSION",
    "_Agent-Context/AGENT-RULES.md",
    "_Agent-Context/TRUNK-BASED-DEVELOPMENT.md",
    # Project hooks (tools/hooks/claude_guard.py): the vault rules as checks, not prompts.
    ".claude/settings.json",
]
EXCLUDE = [
    "tools/__pycache__",
    "tools/tasks-sync",
    "tools/logs",
    # Private finance oversight tooling. Its self-test embeds real figures from a
    # monthly pack, which no word scan can catch; AGENT-RULES says nothing
    # finance-derived reaches the public repo, so the folder never ships.
    "tools/finance",
    ".agents/scripts/__pycache__",
    ".agents/scripts/omarchy_job.sh",
    ".agents/scripts/omarchy_backup.sh",
]
# Empty homes so the layout is visible on first clone.
SKELETON = [
    "Work", "Personal", "Library", "Inbox", "raw", "Archive", "Daily Briefings",
    "Thinking/Daily", "Thinking/Ideas", "Thinking/Beliefs", "Thinking/Decisions",
    ".wiki/summaries", ".wiki/concepts", ".wiki/ideas", ".wiki/digests/queries",
    ".wiki/projects", ".wiki/moc", ".wiki/entities", "logs", ".agents/state",
]
# Private data files replaced by stubs.
STUBS = {
    "_Agent-Context/PROFILE.md": (
        "---\nowner_name: the owner\noutput_lang: en\ncompany_area: Work\nworker_name: worker\n"
        "owner_full_name: the owner\nprivate_segments: \n"
        "protected_homes: Personal/Official Docs, Thinking/_local\n"
        "gitignore_nets: **/Official Docs/, **/* - Health/, **/_local/, **/Security Incidents/\n"
        "---\n\n# Owner profile\n\nRead by tools/owner_profile.py. owner_name and "
        "output_lang (tr or en) shape every prompt; company_area is the folder under Work/ the compiler "
        "treats as your company; worker_name is the commit suffix of an always-on machine, if you run one; "
        "private_segments lists extra folder names that must never be compiled.\n\n"
        "protected_homes lists the folders that must never reach the remote, and gitignore_nets the "
        ".gitignore pattern rules that back up each rule naming a single path. tools/health_check.py "
        "reports on them and tools/tests/test_gitignore_guards.py asserts git really ignores them, so "
        "add a home here and both follow. Put the folders holding health records, identity documents, "
        "finance exports or anything about a child in this list before your first commit: .gitignore "
        "does not untrack, so a file committed once needs history surgery to remove.\n\n## Cross-link rule\n\n"
        "CRITICAL CROSS-LINK RULE: personal and work effects must be surfaced. Whenever a personal topic "
        "affects work or the reverse, link both ways.\n"),
    "_Agent-Context/CONTEXT.md": "# Current context\n\nWho you are, active projects, priorities, open questions. Agents read this first.\n",
    "_Agent-Context/BELIEFS-SUMMARY.md": "# Beliefs summary\n\n## Core Beliefs\n\n(one line per belief, linked to Thinking/Beliefs/)\n",
    "_Agent-Context/PROJECTS-ACTIVE.md": "# Active projects\n\nGenerated by tools/build_dashboard.py from Work/*/notes.md and Personal/*/notes.md.\n",
    "_Agent-Context/TASKS.md": "# Tasks\n\n## Promises\n",
    "_Agent-Context/LEARNINGS.md": (
        "# Learnings\n\nYour standing preferences and the lessons from correcting an agent, for every agent "
        "that works in this vault: Claude sessions (the SessionStart hook loads this file), the Buzz agents "
        "and the reply worker. AGENT-RULES.md sets the rules; this file says how to apply them well, and the "
        "rules win on a conflict. Add an entry each time you correct an agent, in the same shape.\n\n"
        "## Language and style\n\n**1. Example: no em or en dashes anywhere, file names included.** Use a comma, "
        "colon or full stop instead.\nWhy: a strong preference; it kept coming back.\nHow: scan before delivering.\n"),
}
CONTENT_HOMES_IGNORE = """# brainless public engine repo

# Secrets and credentials
*.key
*.pem
*.p12
*service_account*
*_token.json
*.credentials.json
.env

# Privacy: personal identity, health and official documents anywhere in the tree
**/Official Docs/
**/* - Health/
**/*Passport*
**/*Pasaport*
**/Security Incidents/
**/_local/

# Machine noise
.DS_Store
venv/
**/.venv/
__pycache__/
*.pyc
.obsidian/workspace*.json

# --- never absorb vault content ---
Work/*
Personal/*
Library/*
Inbox/*
raw/*
Archive/*
Daily Briefings/*
Thinking/**/*.md
.wiki/summaries/*
.wiki/articles/*
.wiki/concepts/*
.wiki/ideas/*
.wiki/digests/*
.wiki/projects/*
.wiki/moc/*
.wiki/entities/*
.wiki/relationships/*
.wiki/INDEX.md
_Agent-Context/*.md
!_Agent-Context/AGENT-RULES.md
!_Agent-Context/TRUNK-BASED-DEVELOPMENT.md
!_Agent-Context/PROFILE.md
!_Agent-Context/LEARNINGS.md
!**/.gitkeep
logs/*
.agents/state/*
"""

LEAK_PATTERNS = [
    ("identity number (11 digits)", re.compile(r"(?<!\d)\d{11}(?!\d)")),
    ("private key block", re.compile(r"BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY")),
    ("hex secret (64 hex)", re.compile(r"(?<![0-9a-f])[0-9a-f]{64}(?![0-9a-f])")),
    ("bot token", re.compile(r"\d{8,10}:[A-Za-z0-9_-]{35}")),
    ("github token", re.compile(r"gh[pousr]_[A-Za-z0-9]{36}|github_pat_[A-Za-z0-9_]{40,}")),
    ("google api key", re.compile(r"AIza[0-9A-Za-z_-]{35}")),
    ("openai key", re.compile(r"(?<![A-Za-z])sk-(?:proj-)?[A-Za-z0-9]{32,}")),
    ("slack token", re.compile(r"xox[baprs]-[A-Za-z0-9-]{10,}")),
    ("aws access key", re.compile(r"(?<![A-Z0-9])AKIA[0-9A-Z]{16}(?![0-9A-Z])")),
    ("jwt", re.compile(r"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{6,}")),
    ("iban (TR)", re.compile(r"TR\d{24}")),
    ("tailscale ip", re.compile(r"100\.(?:6[4-9]|[7-9]\d|1[01]\d|12[0-7])\.\d{1,3}\.\d{1,3}")),
    ("private ipv4", re.compile(r"(?:192\.168|10\.\d{1,3}|172\.(?:1[6-9]|2\d|3[01]))\.\d{1,3}\.\d{1,3}")),
    ("tailscale host", re.compile(r"[A-Za-z0-9-]+\.ts\.net")),
    ("phone (+90)", re.compile(r"\+90\d{10}")),
    ("e-mail address", re.compile(r"[\w.+-]+@(?!example\.|github\.com|report\.spiky\.ai)[\w-]+\.[\w.]+")),
]
OWNER_WORDS = ("Tunca", "Üçer", "tuncaucer", "kolayik", "Kolay İK", "Kolay IK", "omarchy", "ucer.us")
# Files where the owner may legitimately appear (docs about this deployment).
# README.md is authored in the owner's voice and reviewed by hand; the rest is code.
# The .agents/buzz deployment config carries the worker's real home path as a functional
# value (systemd units, permission globs, the buzz-acp command); genericising it would
# break the running deployment, so those files are allow-listed here instead. LEAK_PATTERNS
# still scans them for real secrets; only the owner-word check is waived.
OWNER_ALLOW = (
    "README.md",
    # The long half of the README, moved out on 2026-09-22: same voice, same review.
    "docs/how-it-works.md",
    # The real setup, moved out of how-it-works on 2026-09-23: the worker's name and the
    # profile's owner name are the point of the page.
    "docs/reference-deployment.md",
    "LICENSE",
    "_Agent-Context/TRUNK-BASED-DEVELOPMENT.md",
    "tools/export_public.py",
    ".agents/buzz/personas/settings.json",
    ".agents/buzz/personas/env.template",
    ".agents/systemd/buzz-persona@.service",
    ".agents/buzz/team_instructions.md",
    # The worker's name is a functional value in these: it is half of the script
    # filenames the units exec (omarchy_job.sh, omarchy_backup.sh) and, in the
    # local inference doc, the name of the box the timings were measured on.
    # Renaming it would break the running deployment and lose the provenance of
    # a benchmark, so only the owner-word check is waived; LEAK_PATTERNS still
    # scans them for real secrets.
    ".agents/systemd/brainless-backup.service",
    ".agents/systemd/brainless-backup.timer",
    ".agents/systemd/brainless-content.service",
    ".agents/systemd/brainless-spiky.service",
    ".agents/systemd/brainless-thinkers.service",
    "docs/local-inference.md",
)


# Real people and companies the vault tracks. Their names are read at scan time from
# private files that never ship, so this file holds none of them, and in the public
# checkout (where those files are absent) the check simply finds no names. Test
# fixtures and prompt examples must use invented names; a first name alone is enough
# to identify a colleague to anyone who knows the company.
REGISTRY_FILES = ("_Agent-Context/entities.md", "_Agent-Context/entity-candidates.md")
PEOPLE_GLOB_DIR = "About People"  # Work/<company>/About People/<team>/<Full Name>.md
# Registered names that are also everyday words in the shipped code and docs.
NAME_COMMON = {"Can", "Doğan", "Zafer", "Metin", "Deniz", "Elif", "Su", "Bayrak", "Advisors", "Financial"}


def registry_names(vault=VAULT):
    """Every name the private registry knows: full names, aliases, and the single
    words inside a person's name (a first name or a surname on its own is a leak)."""
    names = set()
    for f in REGISTRY_FILES:
        try:
            with open(os.path.join(vault, f), errors="replace") as fh:
                lines = fh.read().splitlines()
        except OSError:
            continue
        for line in lines:
            parts = [x.strip() for x in re.sub(r"^- \[.\]\s*", "", line).split("|")]
            if len(parts) < 2 or parts[1] not in ("person", "company"):
                continue
            found = [parts[0].strip("* ")]
            # entities.md: Name | type | aliases | scope. The candidates file puts the scope third.
            if f.endswith("entities.md") and len(parts) > 2:
                found += [a.strip() for a in parts[2].split(",") if a.strip()]
            names.update(found)
            if parts[1] == "person":
                for n in found:
                    names.update(n.split())
    work = os.path.join(vault, "Work")
    if os.path.isdir(work):
        for area in os.listdir(work):
            people = os.path.join(work, area, PEOPLE_GLOB_DIR)
            for _dirpath, _dirs, files in os.walk(people):
                for fn in files:
                    if fn.endswith(".md"):
                        stem = fn[:-3]
                        names.add(stem)
                        names.update(stem.split())
    # The owner has a check of their own, with an allow-list (OWNER_WORDS, OWNER_ALLOW).
    owner = tuple(w.lower() for w in OWNER_WORDS)
    return {n for n in names if len(n) >= 3 and n not in NAME_COMMON and not n.islower()
            and not any(w in n.lower() for w in owner)}


def name_patterns(names):
    """Case-sensitive, whole word, but a Turkish suffix after an apostrophe still counts:
    "Aylin'e" is Aylin."""
    if not names:
        return None
    alts = "|".join(re.escape(unicodedata.normalize("NFC", n)) for n in sorted(names, key=len, reverse=True))
    return re.compile(rf"(?<![\w])(?:{alts})(?![\w])")


def rel(path):
    return os.path.relpath(path, VAULT)


def excluded(relpath):
    return any(relpath == e or relpath.startswith(e + "/") for e in EXCLUDE)


def iter_ship():
    for d in SHIP_DIRS:
        root = os.path.join(VAULT, d)
        if not os.path.isdir(root):
            continue
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = [x for x in dirnames if not excluded(rel(os.path.join(dirpath, x))) and x != "__pycache__"]
            for fn in filenames:
                p = os.path.join(dirpath, fn)
                if not excluded(rel(p)) and not fn.endswith((".pyc", ".log")):
                    yield rel(p)
    for f in SHIP_FILES:
        if os.path.isfile(os.path.join(VAULT, f)):
            yield f


# CI gate written into the public checkout: GitHub Actions runs the same leak
# scan on every push and pull request and fails if anything leaks, so the
# guarantee is mechanical instead of a step someone must remember. It is
# generated here on every export, so it self-heals and never lands in the
# private source tree (where the scan would fail on legitimate owner content).
LEAK_SCAN_WORKFLOW = """name: leak-scan
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Scan the tree for owner references and secrets
        run: python3 tools/export_public.py --scan-only --out .
      - name: Run offline regression tests
        run: python3 -B -m unittest discover -s tools/tests -v
"""


def write_tree(out):
    os.makedirs(out, exist_ok=True)
    n = 0
    for r in iter_ship():
        dst = os.path.join(out, RENAMES.get(r, r))
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(os.path.join(VAULT, r), dst)
        n += 1
    for d in SKELETON:
        os.makedirs(os.path.join(out, d), exist_ok=True)
        open(os.path.join(out, d, ".gitkeep"), "a").close()
    for r, text in STUBS.items():
        dst = os.path.join(out, r)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        with open(dst, "w") as fh:
            fh.write(text)
    with open(os.path.join(out, ".gitignore"), "w") as fh:
        fh.write(CONTENT_HOMES_IGNORE)
    wf = os.path.join(out, ".github", "workflows", "leak-scan.yml")
    os.makedirs(os.path.dirname(wf), exist_ok=True)
    with open(wf, "w") as fh:
        fh.write(LEAK_SCAN_WORKFLOW)
    return n


BINARY_EXT = (".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico")


def leak_scan(out, names=None):
    findings = []
    name_rx = name_patterns(registry_names() if names is None else names)
    for dirpath, dirnames, filenames in os.walk(out):
        dirnames[:] = [d for d in dirnames if d != ".git"]  # git's own metadata is not content
        for fn in filenames:
            p = os.path.join(dirpath, fn)
            r = os.path.relpath(p, out)
            # Raster images are compressed bytes: a word scan of them only finds noise
            # (a PNG matched the e-mail pattern). SVG is text and stays in the scan.
            if fn.lower().endswith(BINARY_EXT):
                continue
            try:
                with open(p, errors="replace") as fh:
                    text = fh.read()
            except OSError:
                continue
            for label, rx in LEAK_PATTERNS:
                for m in rx.finditer(text):
                    findings.append((r, label, m.group(0)[:40]))
            if name_rx:
                for m in name_rx.finditer(unicodedata.normalize("NFC", text)):
                    findings.append((r, "registry name", m.group(0)))
            if not r.startswith(OWNER_ALLOW):
                low = text.lower()
                for w in OWNER_WORDS:
                    if w.lower() in low:  # case-insensitive: catches Omarchy, TUNCA, etc.
                        findings.append((r, "owner reference", w))
    return findings


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", help="destination directory (omit for a dry run)")
    ap.add_argument("--scan-only", action="store_true", help="only scan an existing --out tree")
    ap.add_argument("--update", action="store_true",
                    help="refresh an existing checkout in place: replace everything except .git, keep history")
    args = ap.parse_args()
    if not args.out:
        files = sorted(set(iter_ship()))
        print("\n".join(files))
        print(f"\n{len(files)} files would ship, plus {len(SKELETON)} skeleton dirs and {len(STUBS)} stubs.")
        return
    if not args.scan_only:
        if os.path.exists(args.out) and os.listdir(args.out):
            if not args.update:
                print(f"refusing to write into a non-empty directory: {args.out} (use --update to refresh a checkout)",
                      file=sys.stderr)
                sys.exit(2)
            for name in os.listdir(args.out):
                if name == ".git":
                    continue
                p = os.path.join(args.out, name)
                shutil.rmtree(p) if os.path.isdir(p) and not os.path.islink(p) else os.remove(p)
        n = write_tree(args.out)
        print(f"wrote {n} files to {args.out}")
    findings = leak_scan(args.out)
    if findings:
        print(f"\nLEAK SCAN: {len(findings)} finding(s). Fix before publishing:")
        seen = set()
        for r, label, hit in findings:
            key = (r, label, hit)
            if key in seen:
                continue
            seen.add(key)
            print(f"  {r}: {label}: {hit}")
        sys.exit(1)
    print("leak scan clean")


if __name__ == "__main__":
    main()
